// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD22TNGqE4-dZVfsultwIG2Z0K5ZLGX-sI',
    appId: '1:675963267318:web:16885a0aeb20e8ac6064d7',
    messagingSenderId: '675963267318',
    projectId: 'pyramidmobile-925fa',
    authDomain: 'pyramidmobile-925fa.firebaseapp.com',
    storageBucket: 'pyramidmobile-925fa.firebasestorage.app',
    measurementId: 'G-EGJ4V743QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPlXfWlMHWwY56bBieR6UjimlA6GKibM',
    appId: '1:675963267318:android:9f4fa0efed3215b86064d7',
    messagingSenderId: '675963267318',
    projectId: 'pyramidmobile-925fa',
    storageBucket: 'pyramidmobile-925fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHu79khKR--W0EQr9UNamUXdI7suaeJi4',
    appId: '1:675963267318:ios:aad339fba3e337d16064d7',
    messagingSenderId: '675963267318',
    projectId: 'pyramidmobile-925fa',
    storageBucket: 'pyramidmobile-925fa.firebasestorage.app',
    iosBundleId: 'com.flutterflow.finwallet',
  );
}
